todo_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_apps.urls')),
    path('users/', include('users.urls')),
]

todo_apps/urls.py
from django.urls import path #import path

from . import views #import views

app_name = 'todo_apps'

urlpatterns = [
    #Dodanie strony głównej
    path('', views.index, name='index'),
    path('tasks/', views.tasks, name='tasks'),
    path('all_tasks/', views.all_tasks, name='all_tasks'),
    path('new_task/', views.new_task, name="new_task"),
    path('edit_task/<int:task_id>/', views.edit_task, name="edit_task"),
    path('delete_task/<int:task_id>/', views.delete_task, name="delete_task"),
    path('completed_tasks/', views.completed_tasks, name="completed_tasks"),
    ] 

users/urls.py
from django import views
from django.contrib.auth.views import LoginView
from django.urls import path 
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'users/login.html'), name='login' ),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('edit_password', views.edit_password, name="edit_password"),
    ]

todo_apps/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Project(models.Model):
    project_title = models.CharField(max_length=200)
    assigned_users = models.ManyToManyField(User)

    def __str__(self):
        return self.project_title

class Task(models.Model):
    text_title = models.CharField(max_length=200)
    text_desc = models.TextField(max_length=10000, blank=True, null=True,)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=10000, blank=True, null=True)
    date_due = models.DateField()
    status = models.BooleanField(default=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.text_title



    

todo_apps/forms.py
from django import forms
from .models import Project, Task

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['project_title', 'assigned_users']
        labels = {'project_title': 'Name', 'assigned_users': 'Assigned users'}

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['text_title', 'text_desc', 'comment', 'date_due', 'owner', 'status', 'project']
        labels = {'text_title': 'Title', 'text_desc': 'Description', 'comment': 'Comment', 'date_due': 'Due date', 'owner': 'Owner', 'status': 'Status', 'project': 'Project'}

todo_apps/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Project, Task, User
from .forms import TaskForm
from django.http import Http404


def check_topic_owner(request, task):
    if task.owner != request.user:
        raise Http404




# Delete a task.
@login_required
def delete_task(request, task_id):
    task_to_delete = Task.objects.get(id=task_id)
    task_to_delete.delete()

    #return redirect('todo_apps:tasks')    

# Create your views here.

@login_required
def index(request):
    projects = Project.objects.filter(assigned_users=request.user)
    tasks = Task.objects.filter(project = Project.objects.get(assigned_users=request.user), owner=request.user, status=False) #for badge counter on index.html
    all_tasks = Task.objects.filter(project = Project.objects.get(assigned_users=request.user), status=False)
    context = {'projects': projects,'tasks': tasks, 'all_tasks': all_tasks}
    return render(request, 'todo_apps/index.html', context)

@login_required
def tasks(request):
    tasks = Task.objects.filter(project = Project.objects.get(assigned_users=request.user), owner=request.user, status=False).order_by('date_due') #display tasks that are assigned to the same project as the user
    all_tasks = Task.objects.filter(project = Project.objects.get(assigned_users=request.user), status=False)

    if request.method != 'POST':
        form = TaskForm()
    else:
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todo_apps:tasks')    

    context = {'tasks': tasks, 'all_tasks': all_tasks}
    return render(request, 'todo_apps/tasks.html', context)

@login_required
def all_tasks(request):
    all_tasks = Task.objects.filter(project = Project.objects.get(assigned_users=request.user), status=False).order_by('date_due')
    tasks = Task.objects.filter(project = Project.objects.get(assigned_users=request.user),owner=request.user, status=False)
    context = {'all_tasks': all_tasks, 'tasks': tasks}
    return render(request, 'todo_apps/all_tasks.html', context)

@login_required
def completed_tasks(request):
    completed_tasks = Task.objects.filter(project = Project.objects.get(assigned_users=request.user), status=True).order_by('date_due')
    all_tasks = Task.objects.filter(project = Project.objects.get(assigned_users=request.user), status=False)
    tasks = Task.objects.filter(project = Project.objects.get(assigned_users=request.user), owner=request.user, status=False)
    context = {'completed_tasks': completed_tasks, 'all_tasks': all_tasks, 'tasks': tasks}
    return render(request, 'todo_apps/completed_tasks.html', context)

@login_required
def new_task(request):
    if request.method != 'POST':
        assigned = Project.objects.get(assigned_users=request.user)
        print(assigned)
        form = TaskForm(initial={'owner': request.user, 'project': assigned})
    else:
        form = TaskForm(request.POST)
        if form.is_valid():
            newtask = form.save(commit=False)
            #newtask.owner = request.user
            newtask.project = Project.objects.get(assigned_users=request.user)
            newtask.save()
            # return redirect('todo_apps:tasks') naprawia - usuniecie ładowania w zadań w modalu

    context = {'form': form}
    return render(request, 'todo_apps/new_task.html', context)

@login_required
def edit_task(request, task_id):
    task = Task.objects.get(id=task_id)
    if request.method != 'POST':
        form = TaskForm(instance=task)
    else:
        form = TaskForm(instance=task, data=request.POST)
        if form.is_valid():
            edit_task = form.save(commit=False)
            edit_task.project = Project.objects.get(assigned_users=request.user)
            edit_task.save()
            # return redirect('todo_apps:tasks') usunięcie naprawia bląd ładowania widoku wewnątrz modala


    context = {'task': task, "form": form}
    return render(request, 'todo_apps/edit_task.html', context)

todo_apps/templates/todo_apps/all_tasks.html
{% extends "todo_apps/base.html" %}
{% block content %}

<main class="container formBg">
    <div class="d-flex align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm">
        <svg style="margin-right: .650rem;" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-list-task" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2 2.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5V3a.5.5 0 0 0-.5-.5H2zM3 3H2v1h1V3z"></path>
            <path d="M5 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM5.5 7a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 4a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9z"></path>
            <path fill-rule="evenodd" d="M1.5 7a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V7zM2 7h1v1H2V7zm0 3.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5H2zm1 .5H2v1h1v-1z"></path>
        </svg>
        <div class="lh-1">
            <h1 class="h5 mb-0 text-white lh-1">All Tasks</h1>
        </div>
    </div>

    <div class="mt-3 mb-5 p-4 bg-body rounded shadow-lg">
        <div class="d-block text-end mb-4">
            <button class="myBtn btn btn-outline-primary" hx-get="{% url 'todo_apps:new_task' %}" hx-target="#dialog">+ Add task</a></button>
        </div>

        {% for task in all_tasks %}
            <div class="d-flex mb-4 p-4 task-content">
                <a class="myBtn d-block text-decoration-none" hx-trigger="click" hx-get="{% url 'todo_apps:edit_task' task.id %}" hx-target="#dialog"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square task-content-icon" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"></path>
                  </svg>
                </a>  

            <p class="pb-2 mb-0 small text-muted lh-sm" hx-trigger="click" hx-get="{% url 'todo_apps:edit_task' task.id %}" hx-target="#dialog">
                <a class="myBtn d-block text-decoration-none task-item task-content-h h6"><strong>{{ task.text_title }}</strong></a>
                <small><strong>Due Date:</strong> {{ task.date_due }}</small></br>
                <strong>Assigned to:</strong> {{ task.owner }}
            </p>
            </div>

        {% empty %}
            <p>No tasks added!</p>
        {% endfor %}    
            

                <!-- The Modal -->
                <div id="myModal" class="modal">
                    <div class="alert alert-success alertsuccess" id="alertSuccess" role="alert">
                        <div id="alertText"></div>
                    </div>
                    <div class="alert alert-danger" id="alertDelete"  role="alert">
                        <div id="alertTextDelete"></div>
                    </div>
                    <!-- Modal content -->
                    <div id="dialog" class="modal-content" hx-target="this">
                    </div>
                    
                </div>
    </div>
  
  


</main>



   {% comment %}  <p>Tasks:</p>

    <ul>
        {% for task in tasks %}
            <p><a href="{% url 'todo_apps:edit_task' task.id %}">{{ task }}</a><br>
            {{ task.text_desc }}
            </p>
            <br>
        {% empty %}
            <li>Doesn't have tasks</li>   
        {% endfor %}     
    </ul>
    <a href={% url 'todo_apps:new_task' %}><button>Add new task</button></a>
 {% endcomment %}

{% endblock content %}

todo_apps/templates/todo_apps/base.html
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Tomasz Kaczmarczyk - TaskiDoo!">
    <title>TaskiDoo - PM Tool</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  </head>

  {% if user.is_authenticated %}
  <body class="bg-light">
    
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" style="z-index:4;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'todo_apps:index' %}"><i><b>TaskiDoo</i>!</b></a>
            <button class="navbar-toggler p-0 border-0" type="button" id="hamburgerMenuIcon">
            <span class="navbar-toggler-icon"></span>
            </button>
            <button type="button" class="btn-close btn-close-white" aria-label="Close" id="closeBtn"></button>


            <div class="navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link"></a>
                  </li>
            </ul>
            <ul class="navbar-nav me-0 mb-5 mb-lg-0">
            {% if user.is_authenticated %} 
            <li class="nav-item me-2">
            <a class="nav-link" href="{% url 'users:profile' %}">Logged: <b>{{ user.username }}</b></a>
            </li>   
            <li class="nav-item me-4">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
            </li>
            {% else %}    
            <li class="nav-item me-4">
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
            </li>
            <li class="nav-item me-4">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
            </ul>
            {% endif %}
            </div>
        </div>
        </nav>

        <div class="nav-scroller bg-body shadow-sm">
        <nav class="nav nav-underline">
            <a class="nav-link" id="my_tasks"  href="{% url 'todo_apps:tasks' %}">
              My Tasks
            <span class="badge bg-light text-dark rounded-pill align-text-bottom">{{ tasks.count }}</span>
            </a>
            <a class="nav-link" id="all_tasks" href="{% url 'todo_apps:all_tasks' %}">
              All Tasks
            <span class="badge bg-light text-dark rounded-pill align-text-bottom">{{ all_tasks.count}}</span>
            </a>
            <a class="nav-link" id="completed_tasks" href="{% url 'todo_apps:completed_tasks' %}">Completed Tasks</a>
        </nav>
        </div>

{% endif %}

{% block content %} {% endblock content %}

<footer class="footer text-center text-white">
  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <section class="mb-4">

      <!-- Linkedin -->
      <a
        class="btn btn-link btn-floating btn-lg m-1 social-icon"
        href="https://www.linkedin.com/in/tomasz-kaczmarczyk-4235a31a4/"
        role="button"
        ><i class="fab fa-linkedin"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-link btn-floating btn-lg m-1 social-icon"
        href="https://github.com/TKdev96"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center text-dark p-3 footer-text">
    © 2022 Copyright:
    <a class="text-dark" href="#"><b><i>TaskiDoo</i>!</b></a>
  </div>
  <!-- Copyright -->
</footer>
<!-- HTMX CDN -->
<script src="https://unpkg.com/htmx.org@1.7.0"></script> 
<!-- JS Base-->
<script src="{% static 'js/app.js' %}" type="text/javascript"></script>


  </body>
</html>


       {% comment %}  <p>
            
            <a href="{% url 'todo_apps:tasks' %}">My Tasks</a>
            {% if user.is_authenticated %}
                <a href="{% url 'users:logout' %}">Log out</a>
            {% else %}
                <a href="{% url 'users:login' %}">Log In</a>
            {% endif %}     
        </p>
         {% endcomment %}
           

 
  

todo_apps/templates/todo_apps/completed_tasks.html
{% extends "todo_apps/base.html" %}
{% block content %}

<main class="container formBg mb-4">
    <div class="d-flex align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm">
        <svg style="margin-right: .650rem;" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-list-task" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2 2.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5V3a.5.5 0 0 0-.5-.5H2zM3 3H2v1h1V3z"></path>
            <path d="M5 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM5.5 7a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 4a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9z"></path>
            <path fill-rule="evenodd" d="M1.5 7a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V7zM2 7h1v1H2V7zm0 3.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5H2zm1 .5H2v1h1v-1z"></path>
        </svg>
        <div class="lh-1">
            <h1 class="h5 mb-0 text-white lh-1">Completed Tasks</h1>
        </div>
    </div>

    <div class="mt-3 mb-5 p-4 bg-body rounded shadow-lg">

        {% for task in completed_tasks %}
            <div class="d-flex mb-4 p-4 task-content">
                <a class="myBtn d-block text-decoration-none" hx-trigger="click" hx-get="{% url 'todo_apps:edit_task' task.id %}" hx-target="#dialog"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square task-content-icon" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"></path>
                  </svg>
                </a>  

            <p class="pb-2 mb-0 small text-muted lh-sm" hx-trigger="click" hx-get="{% url 'todo_apps:edit_task' task.id %}" hx-target="#dialog">
                <a class="myBtn d-block text-decoration-none task-item task-content-h h6"><strong>{{ task.text_title }}</strong></a>
                <small><strong>Due Date:</strong> {{ task.date_due }}</small></br>
                <strong>Assigned to:</strong> {{ task.owner }}
            </p>
             </div>

        {% empty %}
            <p>No tasks added!</p>
        {% endfor %}    
            

                <!-- The Modal -->
                <div id="myModal" class="modal">
                    <div class="alert alert-success alertsuccess" id="alertSuccess" role="alert">
                        <div id="alertText"></div>
                    </div>
                    <div class="alert alert-danger" id="alertDelete" role="alert">
                        <div id="alertTextDelete"></div>
                    </div>
                    <!-- Modal content -->
                    <div id="dialog" class="modal-content" hx-target="this">
                    </div>
                    
                </div>
    </div>
  
  


</main>




   {% comment %}  <p>Tasks:</p>

    <ul>
        {% for task in tasks %}
            <p><a href="{% url 'todo_apps:edit_task' task.id %}">{{ task }}</a><br>
            {{ task.text_desc }}
            </p>
            <br>
        {% empty %}
            <li>Doesn't have tasks</li>   
        {% endfor %}     
    </ul>
    <a href={% url 'todo_apps:new_task' %}><button>Add new task</button></a>
 {% endcomment %}

{% endblock content %}

todo_apps/templates/todo_apps/edit_task.html
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% load widget_tweaks %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Tomasz Kaczmarczyk - TaskiDoo!">
    <title>TaskiDoo - PM Tool</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

    <form hx-post="{% url 'todo_apps:edit_task'  task.id %}">
        {% csrf_token %}
        
        <div class="modal-header">
            
          <h5 class="modal-title">Edit Task</h5>          
          <span class="closeX">&times;</span>
        </div>
        <div class="modal-body overflow-auto pb-4">
          <div class="form-check mt-2">
            <strong>Mark as completed</strong>
            {% render_field form.status|attr:"type:checkbox" class="form-check-input" id="flexCheckDefault"  %}
          </div>

            <div class="form-group mt-4">
              <strong>Title: </strong>
              {% render_field form.text_title class="form-control mt-3 form-control-sm" style="max-height: 150px;" %}
            </div>  

            <div class="form-group mt-4">
              <strong>Description: </strong>
              {% render_field form.text_desc class="form-control mt-3 form-control-sm" style="max-height: 110px;" %}
            </div>  

            <div class="form-group mt-4">
              <strong>Comment: </strong>
              {% render_field form.comment class="form-control mt-3 form-control-sm" style="max-height: 80px;" %}  
            </div>  

            <div class="d-flex bd-highlight">
            <div class="form-group mt-4 bd-highlight">  
              <strong>Due Date: </strong>
              {% render_field form.date_due|attr:"type:date" class="form-control mt-3 form-control-sm" style="max-width: 150px;" %}
            </div>
            <div class="form-group mt-4 bd-highlight" style="margin-left: 2.5rem;">
              <strong>Assigned To: </strong>
              {% render_field form.owner|attr:"select" class="form-control mt-3 form-control-sm" %}
            </div>
            {% if request.user.is_superuser %}
            <div class="form-group mt-4 bd-highlight" style="margin-left: 2.5rem;">
              <strong>Project: </strong>
              {% render_field form.project|attr:"select" class="form-control mt-3 form-control-sm" %}
            </div>
            {% endif %}
            </div>

        </div>

        <div class="modal-footer d-flex bd-highlight">
            <div class="flex-grow-1 bd-highlight">
              <button class="btn btn-danger" id="delete-task-prevent">Delete</button>
              <button class="btn btn-danger" id="delete-task" hx-post="{% url 'todo_apps:delete_task' task.id %}">Delete</button>
            </div>   
            <div class="bd-highlight">
                <button class="d-inline btn btn-secondary" id="cancel-task">Cancel</button>
            </div>
            <div class="bd-highlight">    
                <button class="d-inline btn btn-success" id="save-edit-task" type="submit">Confirm</button>
            </div>   
        </div>
      </form>

<!-- JS -->
<script src="{% static 'js/edit_task.js' %}" type="text/javascript"></script>

todo_apps/templates/todo_apps/tasks.html
{% extends "todo_apps/base.html" %}
{% block content %}

<main class="container formBg mb-4">
    <div class="d-flex align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm">
        <svg style="margin-right: .650rem;" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-list-task" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2 2.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5V3a.5.5 0 0 0-.5-.5H2zM3 3H2v1h1V3z"></path>
            <path d="M5 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM5.5 7a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 4a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9z"></path>
            <path fill-rule="evenodd" d="M1.5 7a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V7zM2 7h1v1H2V7zm0 3.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5H2zm1 .5H2v1h1v-1z"></path>
        </svg>
        <div class="lh-1">
            <h1 class="h5 mb-0 text-white lh-1">Assigned to you</h1>
        </div>
    </div>

    <div class="mt-3 mb-5 p-4 bg-body rounded shadow-lg">
        <div class="d-block text-end mb-4">
            <button class="myBtn btn btn-outline-primary" hx-get="{% url 'todo_apps:new_task' %}" hx-target="#dialog">+ Add task</button>
        </div>
            
        {% for task in tasks %}
            <div class="d-flex mb-4 p-4 task-content">
                <a class="myBtn d-block text-decoration-none" hx-trigger="click" hx-get="{% url 'todo_apps:edit_task' task.id %}" hx-target="#dialog"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square task-content-icon" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"></path>
                  </svg>
                </a>  
                

            <p class="pb-2 mb-0 small text-muted lh-sm" hx-trigger="click" hx-get="{% url 'todo_apps:edit_task' task.id %}" hx-target="#dialog">
                <a class="myBtn d-block text-decoration-none task-item task-content-h h6"><strong>{{ task.text_title }}</strong></a>
                <small><strong>Due Date:</strong> {{ task.date_due }}</small></br>
                <strong>Assigned to:</strong> {{ task.owner }}
            </p>
            </div>

        {% empty %}
            <p>No tasks added!</p>
        {% endfor %}    
            

            
                <div id="myModal" class="modal">
                    <div class="alert alert-success alertsuccess" id="alertSuccess" role="alert">
                        <div id="alertText"></div>
                    </div>
                    <div class="alert alert-danger" id="alertDelete" role="alert">
                        <div id="alertTextDelete"></div>
                    </div>
                    <!-- Modal content -->
                    <div id="dialog" class="modal-content" hx-target="this">
                    </div>
                    
                </div>
    </div>
</main>




   {% comment %}  <p>Tasks:</p>

    <ul>
        {% for task in tasks %}
            <p><a href="{% url 'todo_apps:edit_task' task.id %}">{{ task }}</a><br>
            {{ task.text_desc }}
            </p>
            <br>
        {% empty %}
            <li>Doesn't have tasks</li>   
        {% endfor %}     
    </ul>
    <a href={% url 'todo_apps:new_task' %}><button>Add new task</button></a>
 {% endcomment %}

{% endblock content %}