todo_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_apps.urls')),
    path('users/', include('users.urls')),
]

todo_apps/urls.py
from django.urls import path #import path

from . import views #import views

app_name = 'todo_apps'

urlpatterns = [
    #Dodanie strony głównej
    path('', views.index, name='index'),
    path('tasks/', views.tasks, name='tasks'),
    path('all_tasks/', views.all_tasks, name='all_tasks'),
    path('new_task/', views.new_task, name="new_task"),
    path('edit_task/<int:task_id>/', views.edit_task, name="edit_task"),
    path('delete_task/<int:task_id>/', views.delete_task, name="delete_task"),
    path('completed_tasks/', views.completed_tasks, name="completed_tasks"),
    ] 

users/urls.py
from django import views
from django.contrib.auth.views import LoginView
from django.urls import path 
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'users/login.html'), name='login' ),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('edit_password', views.edit_password, name="edit_password"),
    ]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 



class SignUpForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

class UpdateUserForm(forms.ModelForm):
    username = forms.CharField()
    email = forms.EmailField()
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

	

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm, UpdateUserForm, UserCreationForm
from todo_apps.models import Project, User
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages



# Create your views here.
@login_required
def logout_view(request): 
    logout(request)
    return redirect('todo_apps:index')

def register(request):
    if request.method != 'POST':
        form = SignUpForm()
    else:
        form = SignUpForm(data=request.POST) #przekazanie danych formularza do klasy formularza tworzenia użytkownika

        if form.is_valid():
            new_user = form.save() #zapisanie w bazie nazwy użytkownika i hasła(hash)
            project = Project.objects.get(project_title='project_none') #odfiltrowanie i przypisanie defaultowego projektu do zmiennej 
            project.assigned_users.add(new_user) #dodanie nowego użytkownika do defaultowego projektu
            login(request, new_user) #autologowanie utworzonego użytkownika
            return redirect('todo_apps:index') #przekierowanie użytkownika na stronę główną

    context = {'form': form}
    return render(request, 'users/register.html', context)

@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)

        if user_form.is_valid():
            user_form.save()
           #return redirect('users:profile')
    else:
            user_form = UpdateUserForm(instance=request.user)

    context = {'user_form': user_form}
    return render(request, 'users/profile.html', context)

@login_required
def edit_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)  # Important!
            messages.success(request, 'Your password was successfully updated!', extra_tags='alert-success')
            #return redirect('edit_password')
        else:
            messages.error(request, 'Error, please enter passwords again.', extra_tags='alert-danger')    
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'users/edit_password.html', {
        'form': form
    })

users/templates/users/edit_password.html
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% load widget_tweaks %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Tomasz Kaczmarczyk - CEO TaskiDoo!">
    <title>TaskiDoo - PM Tool</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

{% block content %}
<body class="bg-light">
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
  <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'todo_apps:index' %}"><i><b>TaskiDoo</i>!</b></a>
      <button class="navbar-toggler p-0 border-0" type="button" id="hamburgerMenuIcon">
      <span class="navbar-toggler-icon"></span>
      </button>
      <button type="button" class="btn-close btn-close-white" aria-label="Close" id="closeBtn"></button>


      <div class="navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link"></a>
            </li>
          <li class="nav-item">
          
          </li>
      </ul>
      <ul class="navbar-nav me-0 mb-5 mb-lg-0">
      {% if user.is_authenticated %} 
      <li class="nav-item me-2">
        <a class="nav-link" href="{% url 'users:profile' %}">Logged: <b>{{ user.username }}</b></a>
      </li>   
      <li class="nav-item me-4">
          <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
      </li>
      {% else %}    
      <li class="nav-item me-4">
          <a class="nav-link" href="{% url 'users:login' %}">Login</a>
      </li>
      <li class="nav-item me-4">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
      </li>
      </ul>
      {% endif %}
      </div>
  </div>
  </nav>
    


    <div class="container my-4" id="formBg">
    <form class="form-group text-center" hx-post="{% url 'users:edit_password' %}">
        {% csrf_token %}

        
        
        <h5 class="font-weight-normal mb-4 mt-3">Change your password</h5>

        {% if messages %}
            {% for message in messages %}
                <div class="{{ message.tags }} mb-4 mt-3" style="height:50px; border-radius: 7px;" role="alert">
                    <div class="py-3">{{ message }}</div>
                </div>
            {% endfor %}
        {% endif %}

        <div class="form-group row mb-4">
          <label for="id_old_password" class="col-sm-2 col-form-label mb-2"><b>Old Password</b></label>
          <div class="col-sm-10">
            {% render_field form.old_password class="form-control"  type="password" placeholder="Enter Old Password" id="id_old_password" %}
          </div>
        </div>

        <div class="form-group row mb-4">
          <label for="id_new_password1" class="col-sm-2 col-form-label mb-2"><b>New Password</b></label>
          <div class="col-sm-10">
            {% render_field form.new_password1 class="form-control" type="password" placeholder="Enter New Password" id="id_new_password1" %}
          </div>
        </div>

        <div class="form-group row mb-4">
            <label for="id_new_password2" class="col-sm-2 col-form-label mb-2"><b>New Password</b></label>
            <div class="col-sm-10">
                {% render_field form.new_password2 class="form-control" type="password" placeholder="Confirmation New Password" id="id_new_password2" %}
          </div>
        </div>

        <div class="form-group row mb-2">
          <a href="{% url 'users:profile' %}" class="text-decoration-none">Back to profile</a>
        </div>

        
        <button class="btn btn-primary btn-block mt-3" onclick="reloader()"  name="submit">Update password</button>
    </form>
</div>


{% endblock content %} 
<script src="https://unpkg.com/htmx.org@1.7.0"></script> 
<script src="{% static 'js/edit_password.js' %}" type="text/javascript"></script>
</body>
</html>
  

users/templates/users/login.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% load widget_tweaks %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Tomasz Kaczmarczyk - CEO TaskiDoo!">
    <title>TaskiDoo - PM Tool</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>


{% block content %}

    {% if form.errors %}
    <p>Username and password isn't valid!</p>
    {% endif %}
    
    <h5 id="loading" class="font-weight-normal mt-5">Please waiting...</h5>
    <div id="loader"></div>
    <form id="auth-form" class="form-signin text-center" hx-post="{% url 'users:login' %}">
    {% csrf_token %}
    <div class="mt-5">
        <h1><b><i>TaskiDoo</i>!</b></h1>
        <h5 class="font-weight-normal">Please sign in</h5>
        <div class="form-group mt-4">
            <label class="sr-only" for="{{ form.username.id_for_label }}">Login</label>
            {% render_field form.username class="form-control" placeholder="Login" type="text" %}

        </div>
        <div class="form-group">
            <label class="sr-only" for="{{ form.password.id_for_label }}">Password</label>
            {% render_field form.password class="form-control" placeholder="Password" type="password" %}
        </div>

    </div>
    <button class="btn btn-primary btn-lg btn-block" style="width: 300px; max-width: 300 px;" onclick="redirect()" name="submit">Sign In</button>
    <input type="hidden" name="next"  value="{% url 'todo_apps:index' %}" />
    <div class="mt-2">
    <a href="{% url 'users:register' %}">Create an account</a>  
    </div>
  </form>
  
  <script src="https://unpkg.com/htmx.org@1.7.0"></script> 
  <script src="{% static 'js/login.js' %}" type="text/javascript"></script>
  </html>  
{% endblock content %}

users/templates/users/profile.html
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% load widget_tweaks %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Tomasz Kaczmarczyk - CEO TaskiDoo!">
    <title>TaskiDoo - PM Tool</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

{% block content %}
<body class="bg-light">
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'todo_apps:index' %}"><i><b>TaskiDoo</i>!</b></a>
    <button class="navbar-toggler p-0 border-0" type="button" id="hamburgerMenuIcon">
    <span class="navbar-toggler-icon"></span>
    </button>
    <button type="button" class="btn-close btn-close-white" aria-label="Close" id="closeBtn"></button>

    <div class="navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link"></a>
            </li>
          
          </li>
      </ul>
      <ul class="navbar-nav me-0 mb-5 mb-lg-0">
      {% if user.is_authenticated %} 
      <li class="nav-item me-2">
      <a class="nav-link" href="{% url 'users:profile' %}">Logged: <b>{{ user.username }}</b></a>
      </li>   
      <li class="nav-item me-4">
          <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
      </li>
      {% else %}    
      <li class="nav-item me-4">
          <a class="nav-link" href="{% url 'users:login' %}">Login</a>
      </li>
      <li class="nav-item me-4">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
      </li>
      </ul>
      {% endif %}
      </div>
  </div>
  </nav>
  
  <div class="alert alert-success mt-4 text-center" style="margin: 0 auto;" id="alertSuccess" role="alert">
    <div id="alertText"></div>
  </div>
    <div class="container my-4" id="formBg"> 
    <form class="form-group text-center" hx-post="{% url 'users:profile' %}">
        {% csrf_token %}

        <h5 class="font-weight-normal mb-4 mt-2">Edit profile</h5>

        <div class="form-group row mb-4">
          <label for="login" class="col-sm-2 col-form-label mb-2"><b>Login</b></label>
          <div class="col-sm-10">
              {% render_field user_form.username class="form-control" type="text" id="login" %}
          </div>
        </div>

        <div class="form-group row mb-4">
          <label for="email" class="col-sm-2 col-form-label mb-2"><b>Email</b></label>
          <div class="col-sm-10">
              {% render_field user_form.email class="form-control" type="email" id="email" %}
          </div>
        </div>

        <div class="form-group row mb-4">
          <label for="firstname" class="col-sm-2 col-form-label mb-2"><b>First name</b></label>
          <div class="col-sm-10">
              {% render_field user_form.first_name class="form-control" type="text" id="firstname" %}
          </div>
        </div>

        <div class="form-group row mb-4">
          <label for="lastname" class="col-sm-2 col-form-label mb-2"><b>Last name</b></label>
          <div class="col-sm-10">
              {% render_field user_form.last_name class="form-control" type="text" id="lastname" %}
          </div>
        </div>

        <div class="form-group row mb-2">
          <a href="{% url 'users:edit_password' %}" class="text-decoration-none">Change your password</a>
        </div>

        <button class="btn btn-primary btn-block mt-3"  onclick="reloader()" name="submit">Update profile</button>
    </form>
</div>

{% endblock content %} 
<script src="https://unpkg.com/htmx.org@1.7.0"></script> 
<script src="{% static 'js/profile.js' %}" type="text/javascript"></script>
</body>
</html>

users/templates/users/register.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% load widget_tweaks %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Tomasz Kaczmarczyk - CEO TaskiDoo!">
    <title>TaskiDoo - PM Tool</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

{% block content %}
<style>
    #loader {
        border: 6px solid #f3f3f3;
        border-radius: 50%;
        border-top: 6px solid #3498db;
        width: 60px;
        height: 60px;
        -webkit-animation: spin 2s linear infinite; /* Safari */
        animation: spin 2s linear infinite;
        display: none;
        margin-left: 50%;
      }
      
      /* Safari */
      @-webkit-keyframes spin {
        0% { -webkit-transform: rotate(0deg); }
        100% { -webkit-transform: rotate(360deg); }
      }
      
      @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
      }
</style>    

<div id="loader"></div>

    <form id="auth-form" style="margin: auto; max-width:400px; padding-left: 56px; padding-right: 56px;" class="form-group text-center mt-5" hx-post="{% url 'users:register' %}">
        {% csrf_token %}
        <h1><a href="{% url 'todo_apps:index' %}" class="text-decoration-none text-dark"><b><i>TaskiDoo</i>!</b></a></h1>
        <h5 class="font-weight-normal">Please enter login & password</h5>

        
        <div class="form-group mt-4">
                {% render_field form.email class="form-control" placeholder="Email" type="email" %}
        </div>
        <div class="form-group mt-4">
          {% render_field form.username class="form-control" placeholder="Login" type="text" %}
        </div>
        <div class="form-group mt-4">
          {% render_field form.first_name class="form-control" placeholder="First Name" type="text" %}
        </div>
        <div class="form-group mt-4">
          {% render_field form.last_name class="form-control" placeholder="Last Name" type="text" %}
        </div>
        <div class="form-group mt-4">
                {% render_field form.password1 class="form-control" placeholder="Password" type="password" %}
        </div>
        <div class="form-group mt-4">
                {% render_field form.password2 class="form-control" placeholder="Enter the same password" type="password" %}
        </div>

        <button class="btn btn-primary btn-lg btn-block mt-4" style="width: 278px; max-width: 278 px;" onclick="redirect()" name="submit">Register</button>
        <input type="hidden" name="next" value="{% url 'todo_apps:tasks' %}"/>
        
        <div class="mt-2">
          <a href="{% url 'users:login' %}">Back to login</a>  
        </div>
    </form>
</div>
<script src="https://unpkg.com/htmx.org@1.7.0"></script> 
<script>
    var loader = document.getElementById('loader')
    var form = document.getElementById('auth-form')

    function redirect() {
      form.style.display = "none";
      loader.style.display = "block"; 
      setTimeout(() => {
        window.location.href="/"}, 700); 
    }
  </script>
</html>  
{% endblock content %} 